/**
 * Authoritative WoW content → expansion mapping.
 *
 * Used by validateGuides.js to cross-check AI-generated guides:
 * if a guide mentions "Karazhan" but the set is tagged Battle for
 * Azeroth, something is wrong (either the guide hallucinated or
 * the set is mistagged).
 *
 * Coverage focuses on content that uniquely identifies an expansion:
 * raids, dungeons, distinctive zones, faction names, currencies.
 * Generic terms (Honor, Conquest, world quest) are excluded.
 */

// Each entry: lowercase content name → expansion key
const CONTENT_TO_EXPANSION = {
  // ── Classic ────────────────────────────────────────────────────────
  'molten core': 'Classic',
  'onyxia\'s lair': 'Classic',
  'blackwing lair': 'Classic',
  'temple of ahn\'qiraj': 'Classic',
  'ahn\'qiraj': 'Classic',
  'ruins of ahn\'qiraj': 'Classic',
  'naxxramas': 'Classic', // also re-released in WotLK; ambiguous - handled separately
  'stratholme': 'Classic',
  'scholomance': 'Classic',
  'dire maul': 'Classic',
  'blackrock depths': 'Classic',
  'lower blackrock spire': 'Classic',
  'upper blackrock spire': 'Classic',
  'scarlet monastery': 'Classic',
  'sunken temple': 'Classic',
  'maraudon': 'Classic',
  'zul\'farrak': 'Classic',
  'zul\'gurub': 'Classic', // also re-released; primarily classic
  'razorgore': 'Classic',
  'nefarian': 'Classic', // also Cata version
  'ragnaros': 'Classic', // also Firelands
  'c\'thun': 'Classic',
  'kel\'thuzad': 'Classic', // also WotLK
  'thunderfury': 'Classic',
  'sulfuras': 'Classic',
  'dark coven': 'Wrath of the Lich King', // ICC sets

  // ── Burning Crusade ────────────────────────────────────────────────
  'karazhan': 'Burning Crusade', // Legion has Return To Karazhan
  'gruul\'s lair': 'Burning Crusade',
  'magtheridon\'s lair': 'Burning Crusade',
  'serpentshrine cavern': 'Burning Crusade',
  'tempest keep': 'Burning Crusade',
  'the eye': 'Burning Crusade',
  'battle for mount hyjal': 'Burning Crusade',
  'black temple': 'Burning Crusade',
  'sunwell plateau': 'Burning Crusade',
  'sunwell': 'Burning Crusade',
  'zul\'aman': 'Burning Crusade',
  'kael\'thas sunstrider': 'Burning Crusade', // and DF version
  'illidan stormrage': 'Burning Crusade',
  'kil\'jaeden': 'Burning Crusade',
  'mount hyjal': 'Burning Crusade',
  'shattered halls': 'Burning Crusade',
  'shadow labyrinth': 'Burning Crusade',
  'auchenai crypts': 'Burning Crusade',
  'sethekk halls': 'Burning Crusade',
  'mana-tombs': 'Burning Crusade',
  'arcatraz': 'Burning Crusade',
  'mechanar': 'Burning Crusade',
  'botanica': 'Burning Crusade',
  'magisters\' terrace': 'Burning Crusade',
  'outland': 'Burning Crusade',

  // ── Wrath of the Lich King ─────────────────────────────────────────
  'icecrown citadel': 'Wrath of the Lich King',
  'ulduar': 'Wrath of the Lich King',
  'trial of the crusader': 'Wrath of the Lich King',
  'trial of the champion': 'Wrath of the Lich King',
  'obsidian sanctum': 'Wrath of the Lich King',
  'eye of eternity': 'Wrath of the Lich King',
  'ruby sanctum': 'Wrath of the Lich King',
  'vault of archavon': 'Wrath of the Lich King',
  'arthas': 'Wrath of the Lich King',
  'lich king': 'Wrath of the Lich King',
  'sapphiron': 'Wrath of the Lich King',
  'mimiron': 'Wrath of the Lich King',
  'yogg-saron': 'Wrath of the Lich King',
  'algalon': 'Wrath of the Lich King',
  'sindragosa': 'Wrath of the Lich King',
  'professor putricide': 'Wrath of the Lich King',
  'pit of saron': 'Wrath of the Lich King',
  'halls of reflection': 'Wrath of the Lich King',
  'forge of souls': 'Wrath of the Lich King',
  'azjol-nerub': 'Wrath of the Lich King',
  'ahn\'kahet': 'Wrath of the Lich King',
  'gundrak': 'Wrath of the Lich King',
  'oculus': 'Wrath of the Lich King',
  'halls of stone': 'Wrath of the Lich King',
  'halls of lightning': 'Wrath of the Lich King',
  'utgarde keep': 'Wrath of the Lich King',
  'utgarde pinnacle': 'Wrath of the Lich King',
  'culling of stratholme': 'Wrath of the Lich King',
  'drak\'tharon keep': 'Wrath of the Lich King',
  'violet hold': 'Wrath of the Lich King',
  'northrend': 'Wrath of the Lich King',
  'frozen throne': 'Wrath of the Lich King',
  'icecrown': 'Wrath of the Lich King',
  'storm peaks': 'Wrath of the Lich King',
  'sholazar basin': 'Wrath of the Lich King',
  'wintergrasp': 'Wrath of the Lich King',
  'shadowmourne': 'Wrath of the Lich King',
  'crusader\'s coliseum': 'Wrath of the Lich King',

  // ── Cataclysm ──────────────────────────────────────────────────────
  'firelands': 'Cataclysm',
  'dragon soul': 'Cataclysm',
  'bastion of twilight': 'Cataclysm',
  'blackwing descent': 'Cataclysm',
  'throne of the four winds': 'Cataclysm',
  'baradin hold': 'Cataclysm',
  'deathwing': 'Cataclysm',
  'al\'akir': 'Cataclysm',
  'cho\'gall': 'Cataclysm',
  'nefarian and onyxia': 'Cataclysm',
  'omnotron defense system': 'Cataclysm',
  'magmaw': 'Cataclysm',
  'maloriak': 'Cataclysm',
  'atramedes': 'Cataclysm',
  'chimaeron': 'Cataclysm',
  'spine of deathwing': 'Cataclysm',
  'madness of deathwing': 'Cataclysm',
  'baleroc': 'Cataclysm',
  'majordomo staghelm': 'Cataclysm',
  'ragnaros (firelands)': 'Cataclysm',
  'shannox': 'Cataclysm',
  'lord rhyolith': 'Cataclysm',
  'alysrazor': 'Cataclysm',
  'beth\'tilac': 'Cataclysm',
  'grim batol': 'Cataclysm',
  'lost city of tol\'vir': 'Cataclysm',
  'halls of origination': 'Cataclysm',
  'throne of the tides': 'Cataclysm',
  'vortex pinnacle': 'Cataclysm',
  'blackrock caverns': 'Cataclysm',
  'stonecore': 'Cataclysm',
  'deepholm': 'Cataclysm',
  'mount hyjal': 'Cataclysm', // also TBC raid; Cata zone

  // ── Mists of Pandaria ──────────────────────────────────────────────
  'siege of orgrimmar': 'Mists of Pandaria',
  'throne of thunder': 'Mists of Pandaria',
  'heart of fear': 'Mists of Pandaria',
  'terrace of endless spring': 'Mists of Pandaria',
  'mogu\'shan vaults': 'Mists of Pandaria',
  'pandaria': 'Mists of Pandaria',
  'pandaren': 'Mists of Pandaria',
  'lei shen': 'Mists of Pandaria',
  'sha of fear': 'Mists of Pandaria',
  'garrosh hellscream': 'Mists of Pandaria',
  'klaxxi': 'Mists of Pandaria',
  'mantid': 'Mists of Pandaria',
  'jade forest': 'Mists of Pandaria',
  'kun-lai summit': 'Mists of Pandaria',
  'townlong steppes': 'Mists of Pandaria',
  'dread wastes': 'Mists of Pandaria',
  'krasarang wilds': 'Mists of Pandaria',
  'valley of the four winds': 'Mists of Pandaria',
  'vale of eternal blossoms': 'Mists of Pandaria',
  'shado-pan': 'Mists of Pandaria',
  'shado-pan monastery': 'Mists of Pandaria',
  'temple of the jade serpent': 'Mists of Pandaria',
  'stormstout brewery': 'Mists of Pandaria',
  'gate of the setting sun': 'Mists of Pandaria',
  'siege of niuzao temple': 'Mists of Pandaria',
  'mogu\'shan palace': 'Mists of Pandaria',
  'isle of thunder': 'Mists of Pandaria',
  'timeless isle': 'Mists of Pandaria',
  'lei shi': 'Mists of Pandaria',
  'wind lord mel\'jarak': 'Mists of Pandaria',
  'grand empress shek\'zeer': 'Mists of Pandaria',
  'imperial vizier zor\'lok': 'Mists of Pandaria',
  'blade lord ta\'yak': 'Mists of Pandaria',
  'amber-shaper un\'sok': 'Mists of Pandaria',
  'tsulong': 'Mists of Pandaria',
  'protectors of the endless': 'Mists of Pandaria',
  'celestial defenders': 'Mists of Pandaria',
  'kor\'kron': 'Mists of Pandaria',
  'darkspear rebellion': 'Mists of Pandaria',

  // ── Warlords of Draenor ────────────────────────────────────────────
  'highmaul': 'Warlords of Draenor',
  'blackrock foundry': 'Warlords of Draenor',
  'hellfire citadel': 'Warlords of Draenor',
  'draenor': 'Warlords of Draenor',
  'tanaan jungle': 'Warlords of Draenor',
  'gorgrond': 'Warlords of Draenor',
  'talador': 'Warlords of Draenor',
  'spires of arak': 'Warlords of Draenor',
  'nagrand (draenor)': 'Warlords of Draenor',
  'frostfire ridge': 'Warlords of Draenor',
  'shadowmoon valley (draenor)': 'Warlords of Draenor',
  'bloodmaul slag mines': 'Warlords of Draenor',
  'iron docks': 'Warlords of Draenor',
  'auchindoun': 'Warlords of Draenor',
  'shadowmoon burial grounds': 'Warlords of Draenor',
  'skyreach': 'Warlords of Draenor',
  'the everbloom': 'Warlords of Draenor',
  'grimrail depot': 'Warlords of Draenor',
  'imperator mar\'gok': 'Warlords of Draenor',
  'archimonde': 'Warlords of Draenor',
  'gorefiend': 'Warlords of Draenor',
  'kilrogg deadeye': 'Warlords of Draenor',
  'iron reaver': 'Warlords of Draenor',
  'kromog': 'Warlords of Draenor',
  'blackhand': 'Warlords of Draenor',
  'ner\'zhul': 'Warlords of Draenor',
  'teron\'gor': 'Warlords of Draenor',
  'gug\'rokk': 'Warlords of Draenor',
  'skulloc': 'Warlords of Draenor',
  'warlord zaela': 'Warlords of Draenor',
  'yalnu': 'Warlords of Draenor',
  'apexis crystal': 'Warlords of Draenor',
  'garrison': 'Warlords of Draenor',
  'medallion of the legion': 'Warlords of Draenor',

  // ── Legion ─────────────────────────────────────────────────────────
  'antorus': 'Legion',
  'tomb of sargeras': 'Legion',
  'nighthold': 'Legion',
  'emerald nightmare': 'Legion',
  'trial of valor': 'Legion',
  'the nighthold': 'Legion',
  'argus': 'Legion',
  'broken isles': 'Legion',
  'suramar': 'Legion',
  'azsuna': 'Legion',
  'val\'sharah': 'Legion',
  'highmountain': 'Legion',
  'stormheim': 'Legion',
  'broken shore': 'Legion',
  'mage tower': 'Legion',
  'order hall': 'Legion',
  'class hall': 'Legion',
  'illidari': 'Legion',
  'kil\'jaeden (legion)': 'Legion',
  'gul\'dan': 'Legion',
  'xavius': 'Legion',
  'cenarius': 'Legion',
  'nythendra': 'Legion',
  'elerethe renferal': 'Legion',
  'helya': 'Legion',
  'odyn': 'Legion',
  'guarm': 'Legion',
  'court of stars': 'Legion',
  'arcway': 'Legion',
  'maw of souls': 'Legion',
  'vault of the wardens': 'Legion',
  'darkheart thicket': 'Legion',
  'eye of azshara': 'Legion',
  'halls of valor': 'Legion',
  'neltharion\'s lair': 'Legion',
  'black rook hold': 'Legion',
  'cathedral of eternal night': 'Legion',
  'seat of the triumvirate': 'Legion',
  'return to karazhan': 'Legion',
  'wakener\'s cache': 'Legion',
  'aluriel': 'Legion',
  'krosus': 'Legion',
  'star augur etraeus': 'Legion',

  // ── Battle for Azeroth ─────────────────────────────────────────────
  'uldir': 'Battle for Azeroth',
  'crucible of storms': 'Battle for Azeroth',
  'eternal palace': 'Battle for Azeroth',
  'the eternal palace': 'Battle for Azeroth',
  'ny\'alotha': 'Battle for Azeroth',
  'ny\'alotha, the waking city': 'Battle for Azeroth',
  'battle of dazar\'alor': 'Battle for Azeroth',
  'kul tiras': 'Battle for Azeroth',
  'zandalar': 'Battle for Azeroth',
  'tiragarde sound': 'Battle for Azeroth',
  'drustvar': 'Battle for Azeroth',
  'stormsong valley': 'Battle for Azeroth',
  'zuldazar': 'Battle for Azeroth',
  'nazmir': 'Battle for Azeroth',
  'vol\'dun': 'Battle for Azeroth',
  'mechagon island': 'Battle for Azeroth',
  'mechagon': 'Battle for Azeroth',
  'nazjatar': 'Battle for Azeroth',
  'azerite': 'Battle for Azeroth',
  'heart of azeroth': 'Battle for Azeroth',
  'queen azshara': 'Battle for Azeroth',
  'n\'zoth': 'Battle for Azeroth',
  'g\'huun': 'Battle for Azeroth',
  'taloc': 'Battle for Azeroth',
  'mother': 'Battle for Azeroth', // Uldir boss
  'fetid devourer': 'Battle for Azeroth',
  'zek\'voz': 'Battle for Azeroth',
  'vectis': 'Battle for Azeroth',
  'mythrax': 'Battle for Azeroth',
  'jaina proudmoore': 'Battle for Azeroth',
  'siege of boralus': 'Battle for Azeroth',
  'kings\' rest': 'Battle for Azeroth',
  'shrine of the storm': 'Battle for Azeroth',
  'temple of sethraliss': 'Battle for Azeroth',
  'underrot': 'Battle for Azeroth',
  'waycrest manor': 'Battle for Azeroth',
  'freehold': 'Battle for Azeroth',
  'tol dagor': 'Battle for Azeroth',
  'atal\'dazar': 'Battle for Azeroth',
  'motherlode': 'Battle for Azeroth',
  'operation mechagon': 'Battle for Azeroth',
  'warfront': 'Battle for Azeroth',

  // ── Shadowlands ────────────────────────────────────────────────────
  'castle nathria': 'Shadowlands',
  'sanctum of domination': 'Shadowlands',
  'sepulcher of the first ones': 'Shadowlands',
  'shadowlands': 'Shadowlands',
  'oribos': 'Shadowlands',
  'maldraxxus': 'Shadowlands',
  'ardenweald': 'Shadowlands',
  'revendreth': 'Shadowlands',
  'bastion (shadowlands)': 'Shadowlands',
  'the maw': 'Shadowlands',
  'torghast': 'Shadowlands',
  'korthia': 'Shadowlands',
  'zereth mortis': 'Shadowlands',
  'venthyr': 'Shadowlands',
  'kyrian': 'Shadowlands',
  'night fae': 'Shadowlands',
  'necrolord': 'Shadowlands',
  'sinfall': 'Shadowlands',
  'sylvanas windrunner': 'Shadowlands',
  'jailer': 'Shadowlands',
  'denathrius': 'Shadowlands',
  'sire denathrius': 'Shadowlands',
  'kel\'thuzad (shadowlands)': 'Shadowlands',
  'huntsman altimor': 'Shadowlands',
  'sun king\'s salvation': 'Shadowlands',
  'artificer xy\'mox': 'Shadowlands',
  'lords of dread': 'Shadowlands',
  'rygelon': 'Shadowlands',
  'anduin wrynn (shadowlands)': 'Shadowlands',
  'lihuvim': 'Shadowlands',
  'halondrus': 'Shadowlands',
  'painsmith raznal': 'Shadowlands',
  'remnant of ner\'zhul': 'Shadowlands',
  'tarragrue': 'Shadowlands',
  'soulrender dormazain': 'Shadowlands',
  'kel\'thuzad (sanctum)': 'Shadowlands',
  'fatescribe roh-kalo': 'Shadowlands',
  'guardian of the first ones': 'Shadowlands',
  'covenant': 'Shadowlands',
  'reservoir anima': 'Shadowlands',
  'soul ash': 'Shadowlands',
  'soul cinders': 'Shadowlands',
  'cosmic flux': 'Shadowlands',
  'renown': 'Shadowlands', // Renown was introduced in SL; reused in DF/TWW
  'stygia': 'Shadowlands',
  'memory of': 'Shadowlands', // legendary memories
  'theater of pain': 'Shadowlands',
  'plaguefall': 'Shadowlands',
  'mists of tirna scithe': 'Shadowlands',
  'halls of atonement': 'Shadowlands',
  'spires of ascension': 'Shadowlands',
  'sanguine depths': 'Shadowlands',
  'necrotic wake': 'Shadowlands',
  'de other side': 'Shadowlands',
  'tazavesh': 'Shadowlands',

  // ── Dragonflight ───────────────────────────────────────────────────
  'vault of the incarnates': 'Dragonflight',
  'aberrus': 'Dragonflight',
  'amirdrassil': 'Dragonflight',
  'amirdrassil, the dream\'s hope': 'Dragonflight',
  'dragon isles': 'Dragonflight',
  'dracthyr': 'Dragonflight',
  'evoker': 'Dragonflight',
  'fyrakk': 'Dragonflight',
  'sarkareth': 'Dragonflight',
  'raszageth': 'Dragonflight',
  'primalist': 'Dragonflight',
  'valdrakken': 'Dragonflight',
  'waking shores': 'Dragonflight',
  'ohn\'ahran plains': 'Dragonflight',
  'azure span': 'Dragonflight',
  'thaldraszus': 'Dragonflight',
  'forbidden reach': 'Dragonflight',
  'zaralek cavern': 'Dragonflight',
  'emerald dream (dragonflight)': 'Dragonflight',
  'ruby life pools': 'Dragonflight',
  'nokhud offensive': 'Dragonflight',
  'algeth\'ar academy': 'Dragonflight',
  'brackenhide hollow': 'Dragonflight',
  'halls of infusion': 'Dragonflight',
  'neltharus': 'Dragonflight',
  'uldaman: legacy of tyr': 'Dragonflight',
  'dawn of the infinite': 'Dragonflight',
  'flightstones': 'Dragonflight',
  'dragonscale expedition': 'Dragonflight',
  'iskaara tuskarr': 'Dragonflight',
  'maruuk centaur': 'Dragonflight',
  'valdrakken accord': 'Dragonflight',
  'gnarlroot': 'Dragonflight',
  'igira the cruel': 'Dragonflight',
  'volcoross': 'Dragonflight',
  'larodar': 'Dragonflight',
  'nymue': 'Dragonflight',
  'smolderon': 'Dragonflight',
  'tindral sageswift': 'Dragonflight',
  'eranog': 'Dragonflight',
  'terros': 'Dragonflight',
  'sennarth': 'Dragonflight',
  'dathea': 'Dragonflight',
  'kurog grimtotem': 'Dragonflight',
  'broodkeeper diurna': 'Dragonflight',
  'rashok': 'Dragonflight',
  'kazzara': 'Dragonflight',
  'amalgamation chamber': 'Dragonflight',
  'forgotten experiments': 'Dragonflight',
  'sage swift': 'Dragonflight',
  'magmorax': 'Dragonflight',
  'echo of neltharion': 'Dragonflight',
  'scalecommander sarkareth': 'Dragonflight',

  // ── The War Within ─────────────────────────────────────────────────
  'nerub-ar palace': 'The War Within',
  'liberation of undermine': 'The War Within',
  'undermine': 'The War Within',
  'khaz algar': 'The War Within',
  'isle of dorn': 'The War Within',
  'ringing deeps': 'The War Within',
  'hallowfall': 'The War Within',
  'azj-kahet': 'The War Within',
  'dornogal': 'The War Within',
  'earthen': 'The War Within',
  'arathi (war within)': 'The War Within',
  'nerubian': 'The War Within',
  'queen ansurek': 'The War Within',
  'silken court': 'The War Within',
  'broodtwister ovi\'nax': 'The War Within',
  'rasha\'nan': 'The War Within',
  'sikran': 'The War Within',
  'bloodbound horror': 'The War Within',
  'ulgrax': 'The War Within',
  'nexus-princess ky\'veza': 'The War Within',
  'delve': 'The War Within',
  'delves': 'The War Within',
  'brann bronzebeard': 'The War Within', // companion only in TWW
  'zekvir': 'The War Within',
  'undercoin': 'The War Within',
  'undercoins': 'The War Within',
  'resonance crystals': 'The War Within',
  'plunderlord': 'The War Within',
  'plunderstorm': 'The War Within',
  'gallagio': 'The War Within',
  'cartel xy\'exa': 'The War Within',

  // ── Midnight (current) ─────────────────────────────────────────────
  'midnight (expansion)': 'Midnight',
  'quel\'thalas': 'Midnight',
};

// Build lowercase keyword list for fast scanning. Multi-word keys win
// over single-word ones (e.g. "blackwing lair" before "blackwing").
const KEYWORDS = Object.keys(CONTENT_TO_EXPANSION).sort((a, b) => b.length - a.length);

/**
 * Find every WoW content keyword present in the text and return the set
 * of expansions implied by those mentions.
 */
function expansionsMentioned(text) {
  if (!text) return [];
  const lower = text.toLowerCase();
  const found = new Map(); // expansion → [ keywords ]
  for (const kw of KEYWORDS) {
    if (lower.includes(kw)) {
      const exp = CONTENT_TO_EXPANSION[kw];
      if (!found.has(exp)) found.set(exp, []);
      found.get(exp).push(kw);
    }
  }
  return Array.from(found.entries()).map(([expansion, keywords]) => ({
    expansion,
    keywords,
  }));
}

module.exports = { CONTENT_TO_EXPANSION, expansionsMentioned };
